CREATE TYPE job_status AS ENUM (
    'created',
    'pending',
    'done'
);

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_key CHAR(40) NOT NULL,
    current_state_key CHAR(40) NOT NULL,
    status job_status NOT NULL DEFAULT 'created',
    details VARCHAR(1000)
);
